##################################################################################
# Custom aliases
##################################################################################
alias ll='ls -alF'
alias la='ls -a'
alias l='ls -CF'
alias ls='ls -lF --color=auto'
alias grep='grep --color=auto -n'
alias diskspace='du -S | sort -n -r |more'
